apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels: # belongs to deployment
    app: rabbitmq
    tier: db
    project: roboshop

spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod
      app: rabbitmq
      tier: db
      project: roboshop
  template: # This is the pod definition.
    metadata:
      labels:
        app: rabbitmq
        tier: db
        project: roboshop
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec: 
  selector:
     app: rabbitmq
     tier: db
     project: roboshop
  ports:
  - name: rabbitmq-port
    protocol: TCP
    port: 5672 # This port belongs to services
    targetPort: 5672 # This port belongs to container