apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    tier: db
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: roboshop
  template:
    metadata:
      labels:
        app: mysql
        tier: db
        project: roboshop
    spec:
      containers:
      - name: mysql
        image: gspvsr/mysql:1.0.0
        envFrom:  # Fixed indentation
        - configMapRef:
            name: mysql  # Fixed indentation
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec: 
  selector:
     app: mysql
     tier: db
     project: roboshop
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  MYSQL_DATABASE: "cities"
  MYSQL_USER: "shipping"
  MYSQL_PASSWORD: "RoboShop@1"
