apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    app: catalogue
    tier: app
    project: roboshop

spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
      tier: app
      project: roboshop
  template:
    metadata:
      labels:
        app: catalogue
        tier: app
        project: roboshop
    spec:
      containers:
      - name: catalogue
        image: gspvsr/catalogue:1.0.0
        envFrom:
        - configMapRef:
            name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec: 
  selector:
    app: catalogue
    tier: app
    project: roboshop
  ports:
  - name: http
    protocol: TCP
    port: 80 # This is the port for external access
    targetPort: 8080 # This is the port your application is listening on inside the container
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
