apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels: # belongs to deployment
    app: catalogue
    tier: app
    project: roboshop

spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod
      app: catalogue
      tier: app
      project: roboshop
  template: # This is the pod definition.
    metadata:
      labels:
        app: catalogue
        tier: app
        project: roboshop
    spec:
      containers:
      - name: catalogue
        image: gspvsr/catalogue:1.0.0
        envFrom:
        - configMapRef:
            name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
spec: 
  selector:
    app: catalogue
    tier: app
    project: roboshop
  ports:
  - name: catalogue-port
    protocol: TCP
    port: 8080 # This port belongs to services
    targetPort: 8080 # This port belongs to container
---
apiVersion: v1
kind : ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
data:
  MONGO: "true" # we need to keep true in double quotes
  MONGO_URL: "mongodb://mongodb:27017/catalogue" # Protocol:service-name:service-port/schema

  